name: check-plugins-build
on:
  pull_request:
    branches:
      - master

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Validate Plugin build system
      run: ./shell/scripts/test-plugins-build.sh
      shell: bash

    - name: Upload files
      uses: actions/upload-artifact@v3
      with:
        name: test
        path: |
          /tmp/tmp.**/test-app
          !/tmp/tmp.**/test-app/node_modules/
          /tmp/tmp.**/pkg/test-pkg/
          !/tmp/tmp.**/pkg/test-pkg/node_modules/
