name: Deploy to Kubernetes

on: [push]

env:
  # K8S_NAME: ${{ github.event.pull_request.title || 'rancher-deployment' }}
  K8S_NAME: 'rancher-deployment'
  K8S_DIR: $GITHUB_WORKSPACE/k8s
  K8S_CLUSTER_CONFIG: $GITHUB_WORKSPACE/k8s/test.yaml
  DIGITALOCEAN_REGISTRY: 'gleo-registry'
  TAG: $(echo $GITHUB_SHA | head -c7)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Install doctl CLI
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t registry.digitalocean.com/${{ env.DIGITALOCEAN_REGISTRY }}/${{env.K8S_NAME}}:${{env.TAG}} .

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/${{ env.DIGITALOCEAN_REGISTRY }}/${{env.K8S_NAME}}:${{env.TAG}}

    - name: Update deployment file
      run: |
        echo "${{secrets.DIGITALOCEAN_CLUSTER}}" >> $GITHUB_WORKSPACE/k8s/cluster-config.yaml
        sed -i 's|<DIGITALOCEAN_DEPLOYMENT_IMAGE>|registry.digitalocean.com/${{ env.DIGITALOCEAN_REGISTRY }}/'${{env.K8S_NAME}}':'${{env.TAG}}'|' -i 's|<DIGITALOCEAN_DEPLOYMENT_NAME>|'${{env.K8S_NAME}}'|' $GITHUB_WORKSPACE/k8s/deployment.yaml

    - name: Delete existing Deployment from Rancher cluster
      run: |
        kubectl delete deployment ${{env.K8S_NAME}} --kubeconfig="${{env.K8S_CLUSTER_CONFIG}}" --ignore-not-found
        
    - name: Deploy to Rancher cluster
      run: |
        kubectl create deployment ${{env.K8S_NAME}} --image=${{env.K8S_NAME}}:${{env.TAG}} --kubeconfig="${{env.K8S_CLUSTER_CONFIG}}"
        # kubectl apply -f k8s/deployment.yaml --kubeconfig="${{env.K8S_CLUSTER_CONFIG}}"