name: Deploy to Kubernetes

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Install doctl CLI
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t rancher-dashboard .

    - name: Define env var values
      run: |
        echo "${{secrets.DIGITALOCEAN_CLUSTER}}" >> $GITHUB_WORKSPACE/k8s/cluster-config.yaml
        sed -e 's|<DIGITALOCEAN_DEPLOYMENT_NAME>|${{github.event.pull_request.title || 'test-push'}}|' $GITHUB_WORKSPACE/k8s/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl create deployment ${{github.event.pull_request.title || 'test-push'}} --image=rancher-dashboard --kubeconfig="k8s/cluster-config.yaml"

        