name: Deploy to Kubernetes

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
   
    # - name: Build Docker image
    #   run: |
    #     docker build -t rancher-dashboard .

    - name: Define env var values
      run: |
        # Set env vars from secrets, keeping the configuration file abstracted and not displaying values
        sed -e 's|<DIGITALOCEAN_CLUSTER_NAME>|${{secrets.DIGITALOCEAN_CLUSTER_NAME}}|' -e 's|<DIGITALOCEAN_CLUSTER_SERVER>|${{secrets.DIGITALOCEAN_CLUSTER_SERVER}}|' -e 's|<DIGITALOCEAN_CLUSTER_CERTIFICATE>|${{secrets.DIGITALOCEAN_CLUSTER_CERTIFICATE}}|' -e 's|<DIGITALOCEAN_CLUSTER_TOKEN>|${{secrets.DIGITALOCEAN_CLUSTER_TOKEN}}|' $GITHUB_WORKSPACE/k8s/cluster-config.yaml
        # Set run 
        sed -e 's|<DIGITALOCEAN_DEPLOYMENT_NAME>|${{github.event.pull_request.title}}|' $GITHUB_WORKSPACE/k8s/deployment.yaml
    
    - name: Set cluster configuration
      # Needs inlined auth token to work
      run: doctl kubernetes cluster kubeconfig save rancher-deployments

    - name: Deploy to Kubernetes
      run: |
        kubectl cluster-info
        kubectl config view
        kubectl apply -f k8s/deployment.yaml
        
