name: Deploy to Kubernetes

on: [push]

env:
  K8S_NAME: ${{ github.event.pull_request.title || 'test-push' }}
  K8S_PATH: $GITHUB_WORKSPACE/k8s/test.yaml
  TAG: $(echo $GITHUB_SHA | head -c7)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
   
    - name: Install doctl CLI
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_TOKEN }}

    - name: Log in to DigitalOcean Container Registry with short-lived credentials
      run: doctl registry login --expiry-seconds 600

    - name: Build Docker image
      run: |
        docker build -t rancher-dashboard registry.digitalocean.com/gleo-registry/${{env.K8S_NAME}}:${{env.TAG}} .

    - name: Push image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/asb/static-example:${{env.TAG}}

    - name: Update deployment file
      run: |
        echo "${{secrets.DIGITALOCEAN_CLUSTER}}" >> $GITHUB_WORKSPACE/k8s/cluster-config.yaml
        sed -i 's|<DIGITALOCEAN_DEPLOYMENT_NAME>|registry.digitalocean.com/gleo-registry/'${env.K8S_NAME}:'${{env.TAG}}'|' $GITHUB_WORKSPACE/k8s/deployment.yaml

    - name: Delete existing Deployment from Rancher cluster
      run: |
        kubectl delete deployment ${{env.K8S_NAME}} --kubeconfig="${{env.K8S_PATH}}" --ignore-not-found
        
    - name: Deploy to Rancher cluster
      run: |
        kubectl create deployment ${{env.K8S_NAME}} --image=rancher-dashboard --kubeconfig="${{env.K8S_PATH}}"
        # kubectl apply -f k8s/deployment.yaml --kubeconfig="${{env.K8S_PATH}}"