name: E2E test
on:
  pull_request:
      branches:
        - master
  workflow_dispatch:
    environment:
      description: 'Environment to run tests against'
      type: environment
      required: true 
env:
  TEST_USERNAME: admin
  TEST_PASSWORD: password
  CATTLE_BOOTSTRAP_PASSWORD: password
  TEST_BASE_URL: https://127.0.0.1:8005
  API: https://127.0.0.1
jobs:
  test:
    if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install packages
        run: yarn install
      
      - name: Prepare build
        run: yarn e2e:pre-prod
      
      - name: Run tests
        run: yarn e2e:prod

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      
      - uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
  skip-e2e:
    if: "contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
    runs-on: ubuntu-latest
    steps:
      - name: Skipping e2e tests
        run: echo "Skipping E2E tests for this PR as a label ci/skip-e2e was found"