name: Unit test and lint
on:
  - push
  - pull_request
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install packages
        run: yarn install
      
      - name: Run tests
        run: yarn test:ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      
      - name: Install packages
        run: yarn install
      
      - name: Run linters
        run: yarn lint
